SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS grb_player;
DROP TABLE IF EXISTS grb_uniform_order;
DROP TABLE IF EXISTS grb_user;

CREATE TABLE grb_player (
  ID int(11) NOT NULL AUTO_INCREMENT,
  USER_ID int(11) NOT NULL,
  PLAYER_FIRST_NAME varchar(20) DEFAULT NULL,
  PLAYER_LAST_NAME varchar(30) DEFAULT NULL,
  SITE_LOCATION char(2) DEFAULT NULL,
  AGE_GROUP char(3) DEFAULT NULL,
  PRIMARY KEY (ID),
  KEY fk_grb_player_id (USER_ID),
  CONSTRAINT grb_player_ibfk_1 FOREIGN KEY (USER_ID) REFERENCES grb_user (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE grb_uniform_order (
  ORDER_ID int(11) NOT NULL AUTO_INCREMENT,
  USER_ID int(11) NOT NULL,
  PLAYER_ID int(11) NOT NULL,
  JERSEY_SIZE char(2) DEFAULT NULL,
  JERSEY_NUMBER int(11) DEFAULT NULL,
  PANTS_SIZE char(2) DEFAULT NULL,
  PANTS_STYLE char(2) DEFAULT NULL,
  HAT_SIZE char(2) DEFAULT NULL,
  SHOE_SIZE double(3,1) DEFAULT NULL,
  TSHIRT_SIZE char(2) DEFAULT NULL,
  SHORTS_SIZE char(2) DEFAULT NULL,
  SEASON char(2) DEFAULT NULL,
  DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ORDER_ID),
  KEY fk_grb_uniform_order_id (USER_ID),
  KEY fk_grb_uniform_order_player_id (PLAYER_ID),
  CONSTRAINT grb_uniform_order_ibfk_1 FOREIGN KEY (USER_ID) REFERENCES grb_user (ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT grb_uniform_order_ibfk_2 FOREIGN KEY (PLAYER_ID) REFERENCES grb_player (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE grb_user (
  ID int(11) NOT NULL AUTO_INCREMENT,
  USER_LOGIN_ID varchar(50) DEFAULT NULL,
  USER_PASSWORD varchar(160) DEFAULT NULL,
  USER_FIRST_NAME varchar(20) DEFAULT NULL,
  USER_LAST_NAME varchar(30) DEFAULT NULL,
  USER_ADDRESS_1 varchar(30) DEFAULT NULL,
  USER_ADDRESS_2 varchar(30) DEFAULT NULL,
  USER_CITY varchar(30) DEFAULT NULL,
  USER_STATE char(2) DEFAULT NULL,
  USER_ZIP varchar(10) DEFAULT NULL,
  USER_PHONE bigint(20) DEFAULT NULL,
  USER_EMAIL varchar(50) DEFAULT NULL,
  DATE_CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADMIN_USER char(1) NOT NULL DEFAULT 'n',
  PRIMARY KEY (ID)
);

SET FOREIGN_KEY_CHECKS = 1;
